# Generated by Django 4.2.1 on 2023-05-16 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='createdon',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='search',
            name='searche',
        ),
        migrations.AddField(
            model_name='search',
            name='search',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
